<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CidadeSeeder extends Seeder
{
    public function run(): void
    {
        $cidades = [
            ['cid_nome' => 'Acorizal', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Água Boa', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Alta Floresta', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Alto Araguaia', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Alto Boa Vista', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Alto Garças', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Alto Paraguai', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Alto Taquari', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Apiacás', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Araguaiana', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Araguainha', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Araputanga', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Arenápolis', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Aripuanã', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Barão de Melgaço', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Barra do Bugres', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Barra do Garças', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Bom Jesus do Araguaia', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Brasnorte', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Cáceres', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Campinápolis', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Campo Novo do Parecis', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Campo Verde', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Campos de Júlio', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Canabrava do Norte', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Canarana', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Carlinda', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Castanheira', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Chapada dos Guimarães', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Cláudia', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Cocalinho', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Colíder', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Colniza', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Comodoro', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Confresa', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Conquista D\'Oeste', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Cotriguaçu', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Cuiabá', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Curvelândia', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Denise', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Diamantino', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Dom Aquino', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Feliz Natal', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Figueirópolis D\'Oeste', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Gaúcha do Norte', 'cid_uf' => 'MT'],
            ['cid_nome' => 'General Carneiro', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Glória D\'Oeste', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Guarantã do Norte', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Guiratinga', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Indiavaí', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Ipiranga do Norte', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Itanhangá', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Itaúba', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Itiquira', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Jaciara', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Jangada', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Jauru', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Juara', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Juína', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Juruena', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Juscimeira', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Lambari D\'Oeste', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Lucas do Rio Verde', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Luciara', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Marcelândia', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Matupá', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Mirassol d\'Oeste', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nobres', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nortelândia', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nossa Senhora do Livramento', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nova Bandeirantes', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nova Brasilândia', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nova Canaã do Norte', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nova Guarita', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nova Lacerda', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nova Marilândia', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nova Maringá', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nova Monte Verde', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nova Mutum', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nova Nazaré', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nova Olímpia', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nova Santa Helena', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nova Ubiratã', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Nova Xavantina', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Novo Horizonte do Norte', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Novo Mundo', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Novo Santo Antônio', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Novo São Joaquim', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Paranaíta', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Paranatinga', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Pedra Preta', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Peixoto de Azevedo', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Planalto da Serra', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Poconé', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Pontal do Araguaia', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Ponte Branca', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Pontes e Lacerda', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Porto Alegre do Norte', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Porto dos Gaúchos', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Porto Esperidião', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Porto Estrela', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Poxoréu', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Primavera do Leste', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Querência', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Reserva do Cabaçal', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Ribeirão Cascalheira', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Ribeirãozinho', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Rio Branco', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Rondolândia', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Rondonópolis', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Rosário Oeste', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Salto do Céu', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Santa Carmem', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Santa Cruz do Xingu', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Santa Rita do Trivelato', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Santa Terezinha', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Santo Afonso', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Santo Antônio do Leste', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Santo Antônio do Leverger', 'cid_uf' => 'MT'],
            ['cid_nome' => 'São Félix do Araguaia', 'cid_uf' => 'MT'],
            ['cid_nome' => 'São José do Povo', 'cid_uf' => 'MT'],
            ['cid_nome' => 'São José do Rio Claro', 'cid_uf' => 'MT'],
            ['cid_nome' => 'São José do Xingu', 'cid_uf' => 'MT'],
            ['cid_nome' => 'São José dos Quatro Marcos', 'cid_uf' => 'MT'],
            ['cid_nome' => 'São Pedro da Cipa', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Sapezal', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Serra Nova Dourada', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Sinop', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Sorriso', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Tabaporã', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Tangará da Serra', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Tapurah', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Terra Nova do Norte', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Tesouro', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Torixoréu', 'cid_uf' => 'MT'],
            ['cid_nome' => 'União do Sul', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Vale de São Domingos', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Várzea Grande', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Vera', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Vila Bela da Santíssima Trindade', 'cid_uf' => 'MT'],
            ['cid_nome' => 'Vila Rica', 'cid_uf' => 'MT'],
        ];

        DB::table('cidade')->insert($cidades);
    }
}
