version: '3.8'

services:
  php-fpm:
    container_name: seplag-api
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    depends_on:
      - postgres

  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm

  postgres:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  minio-setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 minio minio123) do echo '...waiting...' &&
        sleep 1;
      done;
      mc alias set myminio http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} &&
      mc mb --ignore-existing myminio/${AWS_BUCKET} &&
      mc anonymous set none myminio/${AWS_BUCKET} &&
      exit 0;
      "

volumes:
  postgres_data:
  minio_data:
