version: '3'

services:
  php-fpm:
    build: ./.docker/php
    volumes:
      - ./:/var/www
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    depends_on:
      - postgres

  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm

  postgres:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  postgres_data:
  minio_data:
